/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ll.h"


void
square_prog_1(char *host)
{
	CLIENT *clnt;
	square_out  *result_1;
	node  squareproc_1_arg;
	square_out  *result_2;
	node  fuck_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SQUARE_PROG, SQUARE_VERS1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */



	node * temp = (node *)malloc(sizeof(node));
	temp->val = 100;
	temp->next = NULL;

	node * temp1 = (node *)malloc(sizeof(node)); 
	temp1->next = temp;
	temp1->val = 200;

	



	result_1 = squareproc_1(temp1, clnt);
	if (result_1 == (square_out *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	while(result_1->head!=NULL){
		printf("%d\n", result_1->head->val);
		result_1->head=result_1->head->next;
	}
	// result_2 = fuck_1(&fuck_1_arg, clnt);
	// if (result_2 == (square_out *) NULL) {
	// 	clnt_perror (clnt, "call failed");
	// }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
square_prog_2(char *host)
{
	CLIENT *clnt;
	square_out  *result_1;
	node  fun1_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SQUARE_PROG, SQUARE_VERS2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = fun1_2(&fun1_2_arg, clnt);
	if (result_1 == (square_out *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	square_prog_1 (host);
	//square_prog_2 (host);
exit (0);
}
