/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ll.h"

square_out *
squareproc_1_svc(node *argp, struct svc_req *rqstp)
{
	static square_out  result;

	/*
	 * insert server code here
	 */

	printf("%d\n %d\n" , argp->val , argp->next->val);

	node* tmp=(node*)malloc(sizeof (node));
	tmp->val=555;
	tmp->next=NULL;

	argp->next->next=tmp;
	result.head=argp;
	return &result;
}

square_out *
fuck_1_svc(node *argp, struct svc_req *rqstp)
{
	static square_out  result;

	/*
	 * insert server code here
	 */

	return &result;
}

square_out *
fun1_2_svc(node *argp, struct svc_req *rqstp)
{
	static square_out  result;

	/*
	 * insert server code here
	 */

	return &result;
}
