/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ll.h"

bool_t
xdr_node (XDR *xdrs, node *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->val))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (node), (xdrproc_t) xdr_node))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_square_out (XDR *xdrs, square_out *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->head, sizeof (node), (xdrproc_t) xdr_node))
		 return FALSE;
	return TRUE;
}
