/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ARRAY_H_RPCGEN
#define _ARRAY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct array_in {
	int *value;
	int size;
};
typedef struct array_in array_in;

struct array_out {
	int res;
};
typedef struct array_out array_out;

#define ARRAY_PROG 0x31230000
#define ARRAY_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ARRAYPROC 1
extern  array_out * arrayproc_1(array_in *, CLIENT *);
extern  array_out * arrayproc_1_svc(array_in *, struct svc_req *);
extern int array_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ARRAYPROC 1
extern  array_out * arrayproc_1();
extern  array_out * arrayproc_1_svc();
extern int array_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_array_in (XDR *, array_in*);
extern  bool_t xdr_array_out (XDR *, array_out*);

#else /* K&R C */
extern bool_t xdr_array_in ();
extern bool_t xdr_array_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ARRAY_H_RPCGEN */
