/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nfs.h"

bool_t
xdr_nfs_in (XDR *xdrs, nfs_in *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->command))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->start))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->size))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->command);
		IXDR_PUT_LONG(buf, objp->start);
		IXDR_PUT_LONG(buf, objp->size);
		}
		 if (!xdr_vector (xdrs, (char *)objp->buffer, 1024,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->filename, 2014,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->command))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->start))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->size))
				 return FALSE;

		} else {
		objp->command = IXDR_GET_LONG(buf);
		objp->start = IXDR_GET_LONG(buf);
		objp->size = IXDR_GET_LONG(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->buffer, 1024,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->filename, 2014,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->command))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->start))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->buffer, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->filename, 2014,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nfs_out (XDR *xdrs, nfs_out *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->res, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}
