/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "array.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

array_out *
arrayproc_1(array_in *argp, CLIENT *clnt)
{
	static array_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ARRAYPROC,
		(xdrproc_t) xdr_array_in, (caddr_t) argp,
		(xdrproc_t) xdr_array_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

array_out *
arrayproc_2(array_in *argp, CLIENT *clnt)
{
	static array_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ARRAYPROC,
		(xdrproc_t) xdr_array_in, (caddr_t) argp,
		(xdrproc_t) xdr_array_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
